=== ashenafi-else/digital-visual-twins/JSON/Training/schema.training.json
{
	"$id": "02",
	"$schema": "http://json-schema.org/draft-07/schema#",
	"title": "3D_TO_MACHINE_LEARNING",
	"type": "object",
	"required": [ "product", "angles", "components" ],
	"properties":
	{
		"product":
		{
			"type": "object",
			"description": "The product's information.",
			"required": [ "name", "owner", "last_modified", "version", "angles", "zones", "process" ],
			"properties":
			{
				"name":
				{
					"type": "string",
					"description": "The model's name."
				},
				"owner":
				{
					"type": "string",
					"description": "The model's owner name."
				},
				"brand":
				{
					"type": "string",
					"description": "The model's brand name."
				},
				"collection":
				{
					"type": "string",
					"description": "The model's collection name."
				},
				"designer":
				{
					"type": "string",
					"description": "The model's designer name."
				},
				"last_modified":
				{
					"type": "string",
					"description": "The model's last modification date."
				},
				"version":
				{
					"type": "number",
					"description": "The model's version number."
				},
				"main_material":
				{
					"type": "string",
					"description": "The model's main material."
				},
				"main_color":
				{
					"type": "string",
					"description": "The model's main color."
				},
				"target_category":
				{
					"type": "string",
					"description": "The model's target category."
				},
				"season":
				{
					"type": "string",
					"description": "The model's intended season."
				},
				"tip":
				{
					"type": "string",
					"description": "The model's tip shape."
				},
				"closed":
				{
					"type": "boolean",
					"description": "True if the model's tip is closed."
				},
				"closing":
				{
					"type": "string",
					"description": "The model's type of closing (laces, zip...)."
				},
				"heel_height":
				{
					"type": "number",
					"description": "The model's heel height in cm."
				},
				"shoe_height":
				{
					"type": "number",
					"description": "The model's shoe height in cm."
				},
				"angles":
				{
					"type": "array",
					"minItems": 1,
					"items":
					{
						"angle":
						{
							"type": "string",
							"description": "The view angle from which to generate."
						}
					}
				},
				"zones":
				{
					"type": "array",
					"minItems": 1,
					"items":
					{
						"zone":
						{
							"type": "string",
							"description": "The product zones."
						}
					}
				},
				"process":
				{
					"type": "object",
					"description": "The product's process information.",
					"required": [ ],
					"properties":
					{
						"generator":
						{
							"type": "string",
							"description": "The generator's name."
						},
						"assets":
						{
							"type": "object",
							"description": "The product's assets.",
							"additionalProperties":
							{
								"$ref": "#/definitions/product_asset"
							}
						},
						"cad":
						{
							"type": "string",
							"description": "The source CAD name."
						},
						"rendering":
						{
							"type": "string",
							"description": "The rendering system name."
						},
						"datasets":
						{
							"type": "array",
							"minItem": 0,
							"items":
							{
								"$ref": "#/definitions/dataset"
							}
						}
					}
				}
			}
		},
		"angles":
		{
			"type": "array",
			"minItems": 1,
			"items":
			{
				"$ref": "#/definitions/angle"
			}
		},
		"components":
		{
			"type": "array",
			"minItems": 1,
			"items":
			{
				"$ref": "#/definitions/component"
			}
		},
		"landmarks":
		{
			"type": "array",
			"items":
			{
				"$ref": "#/definitions/landmark"
			}
		}
	},
	"definitions":
	{
		"angle":
		{
			"type": "object",
			"description": "The view angle from which to generate.",
			"required": [ "name", "value" ],
			"properties":
			{
				"name":
				{
					"type": "string",
					"description": "The view angle's name."
				},
				"value":
				{
					"type": "number",
					"description": "The angle value.",
					"minimum": 0,
					"maximum": 360
				},
				"offset":
				{
					"type": "number",
					"description": "The maximum offset from the value.",
					"minimum": 0,
					"maximum": 360
				}
			}
		},
		"component":
		{
			"type": "object",
			"required": [ "name", "variants", "mask_material" ],
			"properties":
			{
				"name":
				{
					"type": "string",
					"description": "The component's name."
				},
				"variants":
				{
					"type": "array",
					"minItems": 1,
					"items":
					{
						"$ref": "#/definitions/variant"
					}
				},
				"mask_material":
				{
					"$ref": "#/definitions/material"
				},
				"landmark_material":
				{
					"$ref": "#/definitions/material"
				}
			}
		},
		"variant":
		{
			"type": "object",
			"required": [ "name", "file", "materials" ],
			"properties":
			{
				"name":
				{
					"type": "string",
					"description": "The variant's name."
				},
				"file":
				{
					"type": "string",
					"description": "The variant 3D geometry's file name."
				},
				"materials":
				{
					"type": "array",
					"minItems": 0,
					"items":
					{
						"$ref": "#/definitions/material"
					}
				}
			}
		},
		"material":
		{
			"type": "object",
			"required": [ "name", "file", "colors" ],
			"properties":
			{
				"name":
				{
					"type": "string",
					"description": "The material's name."
				},
				"file":
				{
					"type": "string",
					"description": "The material's file name."
				},
				"color":
				{
					"type": "array",
					"minItems": 1,
					"items":
					{
						"$ref": "#/definitions/color"
					}
				}
			}
		},
		"color":
		{
			"type": "object",
			"required": [ "name", "code" ],
			"properties":
			{
				"name":
				{
					"type": "string",
					"description": "The color's name."
				},
				"code":
				{
					"type": "string",
					"description": "The color's expanded hex code."
				}
			}
		},
		"landmark":
		{
			"type": "object",
			"required": [ "name", "variants", "landmark_material" ],
			"properties":
			{
				"name":
				{
					"type": "string",
					"description": "The landmark's name."
				},
				"variants":
				{
					"type": "array",
					"minItems": 1,
					"items":
					{
						"$ref": "#/definitions/variant"
					}
				},
				"landmark_material":
				{
					"$ref": "#/definitions/material"
				}
			}
		},
		"product_asset":
		{
			"type": "object",
			"description": "A product's asset.",
			"required": [ "type", "file" ],
			"properties":
			{
				"type":
				{
					"type": "string",
					"description": "The asset's type."
				},
				"file":
				{
					"type": "string",
					"description": "The asset's file."
				}
			}
		},
		"dataset":
		{
			"type": "object",
			"description": "The dataset information.",
			"required": [ "name", "version", "size" ],
			"properties":
			{
				"name":
				{
					"type": "string",
					"description": "The dataset's name."
				},
				"version":
				{
					"type": "number",
					"description": "The dataset's version."
				},
				"size":
				{
					"type": "number",
					"description": "The dataset's number of images."
				}
			}
		}
	}
}

=== ashenafi-else/digital-visual-twins/JSON/Training/avril.training.json
{
	"product":
	{
		"name": "Avril",
		"owner": "Belwest",
		"brand": "Belwest",
		"collection": "Visual Quality Control PoC",
		"last_modified": "27-03-20",
		"version": 1.0,
		"main_material": "suede",
		"main_color": "purple",
		"target_category": "women",
		"season": "",
		"tip": "round",
		"closed": true,
		"closing": "strap",
		"heel_height": 9.0,
		"shoe_height": 15.9,
		"angles":
		[
			"inner"
		],
		"zones":
		[
			"buckle",
			"heel",
			"heel_cap",
			"heelcap",
			"heelcap_stitches",
			"insole",
			"lining",
			"lining_stitches",
			"lining_heelcap",
			"lining_heelcap_stitches",
			"outsole",
			"sole",
			"toecap",
			"toecap_stitches",
			"upper",
			"upper_stitches"
		],
		"process":
		{
			"assets":
			{
				"Avril CAD Model 1": { "type": "sho", "file": "belwest_avril_1937781_upgrade by dxf drawings.sho" },
				"Avril Model 1": { "type": "blend", "file": "female.blend" },
				"Avril Model 2": { "type": "blend", "file": "female_inner.blend" },
				"Avril Materials": { "type": "blend", "file": "female_materials.blend" }
			},
			"cad": "ShoeMaster v. 18",
			"rendering": "Blender scripting by ICOL R&D",
			"datasets":
			[
				{
					"name": "inner_data",
					"version": 1.0,
					"size": 300
				}
			]
		}
	},
	"angles":
	[
		{
			"name": "inner",
			"value": 0.0,
			"offset": 12.5
		}
	],
	"components":
	[
		{
			"name": "toecap",
			"variants":
			[
				{
					"name": "toecap",
					"file": "female_inner.blend",
					"materials":
					[
						{
							"name": "mat_suede",
							"file": "female_materials.blend",
							"colors":
							[
								{ "name": "FF9DA2", "code": "FF9DA2" },
								{ "name": "F5CABF", "code": "F5CABF" },
								{ "name": "CF578A", "code": "CF578A" },
								{ "name": "DB8A06", "code": "DB8A06" },
								{ "name": "FDAA63", "code": "FDAA63" },
								{ "name": "B6ADA5", "code": "B6ADA5" },
								{ "name": "B8CCEA", "code": "B8CCEA" },
								{ "name": "8E9FBC", "code": "8E9FBC" },
								{ "name": "AD7C59", "code": "AD7C59" },
								{ "name": "8B5B29", "code": "8B5B29" }
							]
						},
						{
							"name": "mat_volpiana",
							"file": "female_materials.blend",
							"colors":
							[
								{ "name": "FF9DA2", "code": "FF9DA2" },
								{ "name": "F5CABF", "code": "F5CABF" },
								{ "name": "CF578A", "code": "CF578A" },
								{ "name": "DB8A06", "code": "DB8A06" },
								{ "name": "FDAA63", "code": "FDAA63" },
								{ "name": "B6ADA5", "code": "B6ADA5" },
								{ "name": "B8CCEA", "code": "B8CCEA" },
								{ "name": "8E9FBC", "code": "8E9FBC" },
								{ "name": "AD7C59", "code": "AD7C59" },
								{ "name": "8B5B29", "code": "8B5B29" }
							]
						},
						{
							"name": "mat_nubuk",
							"file": "female_materials.blend",
							"colors":
							[
								{ "name": "FF9DA2", "code": "FF9DA2" },
								{ "name": "F5CABF", "code": "F5CABF" },
								{ "name": "CF578A", "code": "CF578A" },
								{ "name": "DB8A06", "code": "DB8A06" },
								{ "name": "FDAA63", "code": "FDAA63" },
								{ "name": "B6ADA5", "code": "B6ADA5" },
								{ "name": "B8CCEA", "code": "B8CCEA" },
								{ "name": "8E9FBC", "code": "8E9FBC" },
								{ "name": "AD7C59", "code": "AD7C59" },
								{ "name": "8B5B29", "code": "8B5B29" }
							]
						},
						{
							"name": "mat_denim",
							"file": "female_materials.blend",
							"colors":
							[
								{ "name": "FF9DA2", "code": "FF9DA2" },
								{ "name": "F5CABF", "code": "F5CABF" },
								{ "name": "CF578A", "code": "CF578A" },
								{ "name": "DB8A06", "code": "DB8A06" },
								{ "name": "FDAA63", "code": "FDAA63" },
								{ "name": "B6ADA5", "code": "B6ADA5" },
								{ "name": "B8CCEA", "code": "B8CCEA" },
								{ "name": "8E9FBC", "code": "8E9FBC" },
								{ "name": "AD7C59", "code": "AD7C59" },
								{ "name": "8B5B29", "code": "8B5B29" }
							]
						},
						{
							"name": "mat_knitted",
							"file": "female_materials.blend",
							"colors":
							[
								{ "name": "FF9DA2", "code": "FF9DA2" },
								{ "name": "F5CABF", "code": "F5CABF" },
								{ "name": "CF578A", "code": "CF578A" },
								{ "name": "DB8A06", "code": "DB8A06" },
								{ "name": "FDAA63", "code": "FDAA63" },
								{ "name": "B6ADA5", "code": "B6ADA5" },
								{ "name": "B8CCEA", "code": "B8CCEA" },
								{ "name": "8E9FBC", "code": "8E9FBC" },
								{ "name": "AD7C59", "code": "AD7C59" },
								{ "name": "8B5B29", "code": "8B5B29" }
							]
						},
						{
							"name": "mat_sm_pearlsnake",
							"file": "female_materials.blend",
							"colors":
							[
								{ "name": "FF9DA2", "code": "FF9DA2" },
								{ "name": "F5CABF", "code": "F5CABF" },
								{ "name": "CF578A", "code": "CF578A" },
								{ "name": "DB8A06", "code": "DB8A06" },
								{ "name": "FDAA63", "code": "FDAA63" },
								{ "name": "B6ADA5", "code": "B6ADA5" },
								{ "name": "B8CCEA", "code": "B8CCEA" },
								{ "name": "8E9FBC", "code": "8E9FBC" },
								{ "name": "AD7C59", "code": "AD7C59" },
								{ "name": "8B5B29", "code": "8B5B29" }
							]
						}
					]
				}
			],
			"mask_material":
			{
				"name": "mat_flat_color",
				"file": "female_materials.blend",
				"colors":
				[
					{ "name": "FF0000", "code": "FF0000" }
				]
			},
			"landmark_material":
			{
				"name": "mat_flat_color",
				"file": "female_materials.blend",
				"colors":
				[
					{ "name": "Flat Black", "code": "000000" }
				]
			}
 		},
		{
			"name": "toecap_stitches",
			"variants":
			[
				{
					"name": "toecap_stitches",
					"file": "female_inner.blend",
					"materials":
					[
						{
							"name": "mat_cotton",
							"file": "female_materials.blend",
							"colors":
							[
								{ "name": "FF9DA2", "code": "FF9DA2" },
								{ "name": "F5CABF", "code": "F5CABF" },
								{ "name": "CF578A", "code": "CF578A" },
								{ "name": "DB8A06", "code": "DB8A06" },
								{ "name": "FDAA63", "code": "FDAA63" },
								{ "name": "B6ADA5", "code": "B6ADA5" },
								{ "name": "B8CCEA", "code": "B8CCEA" },
								{ "name": "8E9FBC", "code": "8E9FBC" },
								{ "name": "AD7C59", "code": "AD7C59" },
								{ "name": "8B5B29", "code": "8B5B29" }
							]
						}
					]
				}
			],
			"mask_material":
			{
				"name": "mat_flat_color",
				"file": "female_materials.blend",
				"colors":
				[
					{ "name": "00FFFF", "code": "00FFFF" }
				]
			},
			"landmark_material":
			{
				"name": "mat_flat_color",
				"file": "female_materials.blend",
				"colors":
				[
					{ "name": "Flat Black", "code": "000000" }
				]
			}
 		},
		{
			"name": "upper",
			"variants":
			[
				{
					"name": "upper",
					"file": "female_inner.blend",
					"materials":
					[
						{
							"name": "mat_shiny_leather",
							"file": "female_materials.blend",
							"colors":
							[
								{ "name": "B66C6D", "code": "B66C6D" },
								{ "name": "E1A6AD", "code": "E1A6AD" },
								{ "name": "A64570", "code": "A64570" },
								{ "name": "C16C18", "code": "C16C18" },
								{ "name": "DE9353", "code": "DE9353" },
								{ "name": "83786F", "code": "83786F" },
								{ "name": "8FACD8", "code": "8FACD8" },
								{ "name": "6E7CA0", "code": "6E7CA0" },
								{ "name": "946037", "code": "946037" },
								{ "name": "744F28", "code": "744F28" }
							]
						},
						{
							"name": "mat_calf_leather",
							"file": "female_materials.blend",
							"colors":
							[
								{ "name": "B66C6D", "code": "B66C6D" },
								{ "name": "E1A6AD", "code": "E1A6AD" },
								{ "name": "A64570", "code": "A64570" },
								{ "name": "C16C18", "code": "C16C18" },
								{ "name": "DE9353", "code": "DE9353" },
								{ "name": "83786F", "code": "83786F" },
								{ "name": "8FACD8", "code": "8FACD8" },
								{ "name": "6E7CA0", "code": "6E7CA0" },
								{ "name": "946037", "code": "946037" },
								{ "name": "744F28", "code": "744F28" }
							]
						},
						{
							"name": "mat_leather",
							"file": "female_materials.blend",
							"colors":
							[
								{ "name": "B66C6D", "code": "B66C6D" },
								{ "name": "E1A6AD", "code": "E1A6AD" },
								{ "name": "A64570", "code": "A64570" },
								{ "name": "C16C18", "code": "C16C18" },
								{ "name": "DE9353", "code": "DE9353" },
								{ "name": "83786F", "code": "83786F" },
								{ "name": "8FACD8", "code": "8FACD8" },
								{ "name": "6E7CA0", "code": "6E7CA0" },
								{ "name": "946037", "code": "946037" },
								{ "name": "744F28", "code": "744F28" }
							]
						},
						{
							"name": "mat_textile",
							"file": "female_materials.blend",
							"colors":
							[
								{ "name": "B66C6D", "code": "B66C6D" },
								{ "name": "E1A6AD", "code": "E1A6AD" },
								{ "name": "A64570", "code": "A64570" },
								{ "name": "C16C18", "code": "C16C18" },
								{ "name": "DE9353", "code": "DE9353" },
								{ "name": "83786F", "code": "83786F" },
								{ "name": "8FACD8", "code": "8FACD8" },
								{ "name": "6E7CA0", "code": "6E7CA0" },
								{ "name": "946037", "code": "946037" },
								{ "name": "744F28", "code": "744F28" }
							]
						},
						{
							"name": "mat_fabric",
							"file": "female_materials.blend",
							"colors":
							[
								{ "name": "B66C6D", "code": "B66C6D" },
								{ "name": "E1A6AD", "code": "E1A6AD" },
								{ "name": "A64570", "code": "A64570" },
								{ "name": "C16C18", "code": "C16C18" },
								{ "name": "DE9353", "code": "DE9353" },
								{ "name": "83786F", "code": "83786F" },
								{ "name": "8FACD8", "code": "8FACD8" },
								{ "name": "6E7CA0", "code": "6E7CA0" },
